name: Deploy to AWS

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  REACT_APP_S3_URL: ${{ secrets.REACT_APP_S3_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1' # Set this to the Node.js version you are using
    # Run
    - name: Browserlist
      run: npx update-browserslist-db@latest

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the React project
    - name: Build
      run: npm run build
      env:
        CI: false # This line overrides the CI environment variable

    # More steps for deploying to AWS depending on the service 
    # you are using to deploy the app (e.g., S3, Elastic Beanstalk, Amplify)
    # Here is an example of deploying to S3

    - name: Deploy to Amazon S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} # for example, us-east-2

    - name: Sync files to S3
      run: aws s3 sync build/ ${{ secrets.AWS_S3_BUCKET }}
